import io
import re
import shutil
import subprocess
import zipfile
import os
from pathlib import Path
from typing import Any, Dict, List
from fastapi import HTTPException, UploadFile # Keep HTTPException if used elsewhere, UploadFile is used

from db_connection.qdrant import QdrantDBManager, COLLECTION_NAME 
from dto.value_objects import ChunkResponse, CodeChunk, QueryResponse, UserQueryAnalysisType, LLMQueryResponse, CodeReference
from langugae_processors.php_processor import LaravelProcessor 
from model_interfaces.embedding_model import EmbeddingModel
from model_interfaces.gemini_model import GeminiModel
from model_interfaces.prompts import gemini_prompts
from utils.logger import LOGGER
from utils.utility import get_file_type

import patch
from unidiff import PatchSet
from typing import List, Dict, Any
from difflib import SequenceMatcher

class ChatAssistantService():
    """
    Service class for handling chat assistant operations.
    Service class for handling chat assistant operations.
    This will encapsulate the logic for uploading, processing,
    and querying codebases.
    """
    def __init__(self):
        self.embedding_model = EmbeddingModel()
        self.vector_store = QdrantDBManager()
        try:
            self.llm_model = GeminiModel()
        except Exception as e: 
            LOGGER.info(f"Failed to initialize Gemini Model: {e}. LLM features will be unavailable.")
            self.llm_model = None
        self.php_processor = LaravelProcessor()  # Initialize once to reuse

    async def process_uploaded_zip(self, zip_file: UploadFile, description: str) -> list[str]:
        """
        Handles the end-to-end process of receiving a zip file,
        saving, extracting, and initiating processing (parsing, embedding, storage).

        Args:
            zip_file (UploadFile): The uploaded zip file.
            description (str): Description of the codebase.

        Returns:
            list[str]: A list of file paths that were extracted.

        """
        LOGGER.info("Started codebase Processing")
        # project_path = r"D:/codes/langGraph_venv/code_assistant/temp_code_uploads/leave-management-laravel"
        project_path =  self.save_uploaded_zip(zip_file, description)
        result = await self.process_codebase(project_path, description)
        return True

    
    

    async def process_codebase(self, project_path: str, description: str) -> List[ChunkResponse]: # Adjusted return type for clarity, though caller ignores it
        # self.lang_processor = LaravelProcessor(project_path)
        # chunks = self.lang_processor.chunk_codebase()

        self.php_processor = LaravelProcessor()
        code_chunks: List[CodeChunk] = self.php_processor.analyze_codebase(project_path)
        
        if not code_chunks:
            LOGGER.info("No code chunks were generated by the processor.")
            return [] # Return empty list if no chunks

        # Extract the actual code content for embedding
        contents_to_embed = [chunk.content for chunk in code_chunks]
        embeddings = self.embedding_model.embed_chunks(contents_to_embed)

        if not embeddings or len(embeddings) != len(code_chunks):
            LOGGER.info(f"Embedding failed or mismatch. Expected {len(code_chunks)} embeddings, got {len(embeddings) if embeddings else 0}.")
            return [] # Return empty list on embedding failure

        # Use the full chunk data (as dictionaries) for payloads in Qdrant
        payloads = [chunk.model_dump() for chunk in code_chunks] # Use .model_dump() for Pydantic models
        success = self.vector_store.save_embeddings(embeddings, payloads)

        if not success:
            LOGGER.info("Failed to save embeddings to vector store.")
            return [] # Return empty list on storage failure
        return code_chunks # Return the processed chunks

                            
    def save_uploaded_zip(self, file: UploadFile, description: str) -> str:
        """
        Saves the uploaded zip file, extracts its contents.
        Returns a list of full paths to the extracted files.
        """
        #create temp folder th root level of the project
        TEMP_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "temp_code_uploads")
        # Ensure TEMP_DIR exists (it should be created by main.py on startup)
        if not os.path.exists(TEMP_DIR):
            os.makedirs(TEMP_DIR, exist_ok=True)
            LOGGER.info(f"Warning: TEMP_DIR '{TEMP_DIR}' was created by api_router.py. It should ideally be managed by main.py startup.")


        extracted_file_paths = []
        temp_zip_path = os.path.join(TEMP_DIR, file.filename)
        # Ensure extraction path is unique if multiple zips with same name are uploaded (though current logic overwrites)
        extraction_base_name = os.path.splitext(file.filename)[0]
        extraction_path = os.path.join(TEMP_DIR, extraction_base_name)

        try:
            # Save the uploaded zip file
            with open(temp_zip_path, "wb") as buffer:
                shutil.copyfileobj(file.file, buffer)

            # Create extraction directory, removing if it already exists to ensure clean extraction
            if os.path.exists(extraction_path):
                shutil.rmtree(extraction_path)
            os.makedirs(extraction_path, exist_ok=True)

            with zipfile.ZipFile(temp_zip_path, 'r') as zip_ref:
                zip_ref.extractall(extraction_path)
                # Get list of extracted files (full paths)
                for item_name in zip_ref.namelist():
                    full_item_path = os.path.join(extraction_path, item_name)
                    extracted_file_paths.append(full_item_path)

            LOGGER.info(f"Received description for {file.filename}: {description}")
            LOGGER.info(f"Extracted files for {file.filename} to: {extraction_path}")

            # Clean up the temporary zip file after extraction
            os.remove(temp_zip_path)

        except Exception as e:
            # Clean up in case of error
            if os.path.exists(temp_zip_path):
                os.remove(temp_zip_path)
            # If extraction path was created but extraction failed or was partial, clean it up
            if os.path.exists(extraction_path) and not any(os.path.exists(p) for p in extracted_file_paths):
                shutil.rmtree(extraction_path)
            raise HTTPException(status_code=500, detail=f"Failed to process zip file '{file.filename}': {str(e)}")
        finally:
            # Ensure the file object is closed
            if hasattr(file, 'file') and file.file:
                file.file.close()

        return extraction_path

    def query_for_semantic_search(self, query: str, top_k: int = 5) -> QueryResponse:
        """
        Embeds the user query and searches for similar code chunks in Qdrant.

        Args:
            query (str): The user's question/query string.
            top_k (int): The number of top similar chunks to retrieve.

        Returns:
            QueryResponse: An object containing the original question, a list of
                           relevant chunk responses, and the count of found chunks.
        """
        original_user_query = query # Store the original query

        if not original_user_query:
            return QueryResponse(
                question=original_user_query, 
                llm_answer=LLMQueryResponse(explanation="Query was empty.", code_references=[]), 
                retrieved_chunks=[], 
                relevant_chunks_found=0)

        processed_query_for_search = original_user_query

        if self.llm_model:
            LOGGER.info(f"Analyzing query with LLM: '{original_user_query}'")
            try:
                # GeminiModel.analyze_query now returns a parsed UnifiedQueryAnalysis object
                analysis_result = self.llm_model.analyze_query(original_user_query)
                LOGGER.info(f"LLM analysis result: type='{analysis_result.type.value}', response='{analysis_result.response}'")

                if analysis_result.type == UserQueryAnalysisType.GENERAL_ANSWER:
                    LOGGER.info(f"LLM provided direct answer: {analysis_result.response}")
                    return QueryResponse(
                        question=original_user_query,
                        llm_answer=LLMQueryResponse(explanation=analysis_result.response, code_references=[]),
                        retrieved_chunks=[],
                        relevant_chunks_found=0
                    )
                elif analysis_result.type == UserQueryAnalysisType.REFINED_QUERY:
                    if analysis_result.response and analysis_result.response.strip():
                        processed_query_for_search = analysis_result.response
                        LOGGER.info(f"LLM refined query to: '{processed_query_for_search}'")
                    else:
                        LOGGER.info("LLM returned an empty refined query, using original.")
                else:
                    LOGGER.info(f"LLM analysis returned unknown type: '{analysis_result.type.value}'. Proceeding with original query.")

            except Exception as e:
                LOGGER.error(f"Error during LLM query analysis: {e}. Proceeding with original query.")
        else:
            LOGGER.info("LLM model not available for query pre-processing.")

        # --- Semantic Search with processed_query_for_search ---
        LOGGER.info(f"Embedding processed query for search: '{processed_query_for_search}'")
        query_embedding_list = self.embedding_model.embed_chunks([processed_query_for_search])

        if not query_embedding_list:
            LOGGER.info("Could not generate embedding for the query.")
            return QueryResponse(
                question=original_user_query, 
                llm_answer=LLMQueryResponse(explanation="Could not generate embedding for the query.", code_references=[]), 
                relevant_chunks_found=0, 
                retrieved_chunks=[])
        
        query_embedding = query_embedding_list[0]

        LOGGER.info(f"Searching Qdrant for top {top_k} similar chunks based on: '{processed_query_for_search}'")
        similar_chunks_payloads = self.vector_store.search_similar_chunks(embedding=query_embedding, limit=top_k)
        
        retrieved_chunk_responses: List[ChunkResponse] = []
        code_chunks_for_llm: List[Dict[str, str]] = []

        if similar_chunks_payloads:
            for payload in similar_chunks_payloads:
                file_name = payload.get("file_path", "Unknown")
                chunk_content = payload.get("content", "No content available for this chunk.")
                
                retrieved_chunk_responses.append(
                    ChunkResponse(file_name=file_name, chunk=chunk_content)
                )
                code_chunks_for_llm.append({
                    "file_path": file_name,
                    "content": chunk_content
                })
        
        # --- Generate Final Answer using LLM with context (if any) ---
        final_llm_answer: LLMQueryResponse # Type hint
        if self.llm_model:
            if code_chunks_for_llm: # If chunks were found
                LOGGER.info(f"Sending original query {original_user_query} and {len(code_chunks_for_llm)} chunks to LLM for final answer...")
                final_llm_answer = self.llm_model.generate_response(user_query=original_user_query, context_chunks=code_chunks_for_llm)
            else: # No relevant chunks found after search
                LOGGER.info(f"No relevant chunks found. Sending original query {original_user_query} to LLM without specific context chunks.")
                final_llm_answer = self.llm_model.generate_response(user_query=original_user_query, context_chunks=[])
        elif not self.llm_model: # LLM model was never available
            final_llm_answer = LLMQueryResponse(
                explanation="LLM model is not available to generate an answer.",
                code_references=[]
            )
        else: # Should not be reached if logic is correct, but as a fallback
            final_llm_answer = LLMQueryResponse(
                explanation="Could not generate an answer using the LLM due to an unexpected state.",
                code_references=[]
            )
        

        return QueryResponse(
            question=original_user_query, # Always return the original question
            llm_answer=final_llm_answer,
            retrieved_chunks=retrieved_chunk_responses,
            relevant_chunks_found=len(retrieved_chunk_responses)
        )

    #new method for qdrant updation 
    def overwrite_chunk_in_file(self, file_path: str, start_line: int, end_line: int, new_content: str, project_root: str) -> Dict[str, Any]:
        """
        Overwrites a specific chunk in a file between start_line and end_line with new_content.

        Args:
            file_path (str): Relative path to the file (e.g., 'app/Http/Controllers/LeaveController.php').
            start_line (int): Starting line number of the chunk (1-based).
            end_line (int): Ending line number of the chunk (1-based).
            new_content (str): The new content to write.
            project_root (str): The root directory of the project.

        Returns:
            Dict[str, Any]: Result of the operation with status and message.
        """

        try:
            # Read the original file
            
            with open(file_path, "r", encoding="utf-8") as f:
                lines = f.readlines()

            # Validate line numbers (convert to 0-based indexing for Python)
            if start_line < 1 or end_line > len(lines) or start_line > end_line:
                return {"status": "error", "message": f"Invalid line range: start_line={start_line}, end_line={end_line}, file_lines={len(lines)}"}

            # Replace the chunk (start_line and end_line are 1-based, so adjust for 0-based indexing)
            start_idx = start_line - 1
            end_idx = end_line  # end_line is inclusive in the chunk, exclusive in slice
            # Split new_content into lines, ensuring it ends with a newline
            new_lines = new_content.strip().splitlines(keepends=False)
            new_lines = [line + "\n" for line in new_lines]
            # Adjust indentation to match the first line of the original chunk
            original_indent = len(lines[start_idx]) - len(lines[start_idx].lstrip())
            new_lines = [" " * original_indent + line.lstrip() for line in new_lines]
            # Replace the lines
            lines[start_idx:end_idx] = new_lines

            # Write the modified content back to the file
            with open(file_path, "w", encoding="utf-8") as f:
                f.writelines(lines)

            return {"status": "success", "message": f"Successfully overwrote chunk in {file_path} from line {start_line} to {end_line}"}

        except Exception as e:
            return {"status": "error", "message": f"Failed to overwrite chunk in {file_path}: {str(e)}"}

    def update_qdrant_after_file_change(self, file_path: str) -> Dict[str, Any]:
        """
        Updates the Qdrant database with new chunks after a file has been modified.

        Args:
            file_path (str): The relative path to the modified file.

        Returns:
            Dict[str, Any]: Result of the update operation.
        """
        try:
            # Since LaravelProcessor works on directories, we'll need to trick it into processing a single file
            # We'll use the appropriate method based on the file type
            
            file_path_obj = Path(file_path)
            file_type = get_file_type(file_path)

            # Clear existing chunks in the processor to avoid appending duplicates
            self.php_processor.chunks = []

            # Parse the single file
            if file_type == "blade_template":
                self.php_processor._parse_blade_file(file_path_obj)
            elif file_type == "route":
                self.php_processor._parse_route_file(file_path_obj)
            else:
                self.php_processor._parse_php_file(file_path_obj, file_type)

            new_chunks = self.php_processor.chunks
            LOGGER.info(f"Generated {len(new_chunks)} new chunks for {file_path}")

            if not new_chunks:
                LOGGER.warning(f"No new chunks generated for {file_path}. Qdrant not updated.")
                return {"status": "warning", "message": f"No new chunks generated for {file_path}"}

            # Step 2: Generate new embeddings
            contents_to_embed = [chunk.content for chunk in new_chunks]
            embeddings = self.embedding_model.embed_chunks(contents_to_embed)

            if not embeddings or len(embeddings) != len(new_chunks):
                LOGGER.error(f"Embedding failed or mismatch. Expected {len(new_chunks)} embeddings, got {len(embeddings) if embeddings else 0}.")
                return {"status": "error", "message": "Failed to generate embeddings for new chunks"}

            # Step 3: Delete old chunks from Qdrant
            success = self.vector_store.delete_chunks_by_file_path(file_path)
            if not success:
                LOGGER.error(f"Failed to delete old chunks for {file_path} from Qdrant.")
                return {"status": "error", "message": f"Failed to delete old chunks for {file_path} from Qdrant"}

            # Step 4: Upsert new chunks to Qdrant
            payloads = [chunk.model_dump() for chunk in new_chunks]
            success = self.vector_store.save_embeddings(embeddings, payloads)
            if not success:
                LOGGER.error(f"Failed to upsert new chunks for {file_path} to Qdrant.")
                return {"status": "error", "message": f"Failed to upsert new chunks for {file_path} to Qdrant"}

            LOGGER.info(f"Successfully updated Qdrant with {len(new_chunks)} new chunks for {file_path}")
            return {"status": "success", "message": f"Successfully updated Qdrant with {len(new_chunks)} new chunks for {file_path}"}

        except Exception as e:
            LOGGER.error(f"Error updating Qdrant for file {file_path}: {e}")
            return {"status": "error", "message": f"Error updating Qdrant for file {file_path}: {str(e)}"}

    def suggest_and_apply_code_update_replace(self, query: str) -> Dict[str, Any]:
        """
        PoC method to suggest and apply code changes via diff.
        Skips LLM analysis type check and directly performs search -> diff generation -> diff application.
        """
        self.current_project_path='/root/code_assistant/temp_code_uploads/leave-management-laravel'
        if not self.current_project_path:
            return {"status": "error", "message": "No codebase has been uploaded yet. Please upload a zip file first."}

        # 1. Perform Semantic Search
        processed_query_for_search = query # Skip analysis for PoC
        try:
            query_embedding_list = self.embedding_model.embed_chunks([processed_query_for_search])
        except Exception as e:
             return {"status": "error", "message": f"Error generating embedding for the query: {e}"}

        if not query_embedding_list:
            return {"status": "error", "message": "Could not generate embedding for the query."}

        query_embedding = query_embedding_list[0]
        LOGGER.info(f"Searching Qdrant for top chunks for update query: '{processed_query_for_search}'")
        similar_chunks_payloads = self.vector_store.search_similar_chunks(embedding=query_embedding, limit=8) # Limit can be adjusted

        if not similar_chunks_payloads:
             return {"status": "info", "message": "No relevant code chunks found for the query. Cannot suggest changes."}

        code_chunks_for_llm = [{
            "file_path": payload.get("file_path", "Unknown"),
            "content": payload.get("content", "No content available for this chunk."),
            "start_line": payload.get("start_line", 0),  # Extract start_line, default to 0
            "end_line": payload.get("end_line", 0)
        } for payload in similar_chunks_payloads]

        
        try:
            idx = self.llm_model.select_best_chunk_index(
                user_query=query,
                chunks=similar_chunks_payloads,
                prompt_template=gemini_prompts.CHUNK_SELECTION_PROMPT
            )
            LOGGER.info(f"Selected chunk index: {idx}")
            chunk = similar_chunks_payloads[idx]
        except Exception as e:
            LOGGER.error(f"Error selecting best chunk index with LLM: {e}. Defaulting to first chunk.")
            idx = 0
            chunk = similar_chunks_payloads[idx]

        # 2. Generate the Modified Code
        try:
            modified_code = self.llm_model.generate_modified_code(user_query=query, context_chunks=code_chunks_for_llm)
            LOGGER.info(f"LLM generated modified code:\n{modified_code}")

            # Check if the LLM returned a request for missing chunks
            if modified_code.strip() == "Need the model chunk to validate fields.":
                return {"status": "error", "message": "LLM requires the model chunk to proceed with modifications."}

            # Basic validation to ensure the output looks like a PHP method
            if not modified_code.strip().startswith("public function"):
                return {"status": "error", "message": "LLM did not generate a valid PHP method.", "modified_code": modified_code}

        except Exception as e:
            return {"status": "error", "message": f"Error generating modified code with LLM: {e}"}

        # 3. Apply the Modified Code by Overwriting the Chunk
        # Assume the first chunk is the most relevant (you can improve this logic if needed)
        target_chunk = code_chunks_for_llm[idx]
        file_path = target_chunk["file_path"]
        start_line = target_chunk["start_line"]
        end_line = target_chunk["end_line"]
       
        if start_line == 0 or end_line == 0:
            return {"status": "error", "message": "Chunk does not contain valid start_line or end_line information."}

        try:
            
            apply_result = self.overwrite_chunk_in_file(
                file_path=file_path,
                start_line=start_line,
                end_line=end_line,
                new_content=modified_code,
                project_root=self.current_project_path
            )
            if apply_result["status"] != "success":
                return {
                    "status": "error",
                    "message": apply_result["message"],
                    "modified_code": modified_code
                }

            # 4. Update Qdrant with the new chunks
            update_result = self.update_qdrant_after_file_change(file_path)
            if update_result["status"] != "success":
                LOGGER.warning(f"Qdrant update failed after applying changes: {update_result['message']}")
                return {
                    "status": "warning",
                    "message": f"Code update applied, but Qdrant update failed: {update_result['message']}",
                    "modified_code": modified_code
                }

            return {
                "status": "success",
                "message": f"Code update applied and Qdrant updated: {apply_result['message']}",
                "modified_code": modified_code
            }
        
        except Exception as e:
            return {"status": "error", "message": f"Error applying modified code: {e}", "modified_code": modified_code}

    # restored the original approach function
    def suggest_and_apply_code_update(self, query: str) -> Dict[str, Any]:
        """
        PoC method to suggest and apply code changes via diff.
        Skips LLM analysis type check and directly performs search -> diff generation -> diff application.
        """
        self.current_project_path='/root/code_assistant'
        # self.current_project_path='D:/codes/langGraph_venv/code_assistant'
        if not self.current_project_path:
            return {"status": "error", "message": "No codebase has been uploaded yet. Please upload a zip file first."}

        # 1. Perform Semantic Search
        processed_query_for_search = query # Skip analysis for PoC
        try:
            query_embedding_list = self.embedding_model.embed_chunks([processed_query_for_search])
        except Exception as e:
             return {"status": "error", "message": f"Error generating embedding for the query: {e}"}

        if not query_embedding_list:
            return {"status": "error", "message": "Could not generate embedding for the query."}

        query_embedding = query_embedding_list[0]
        LOGGER.info(f"Searching Qdrant for top chunks for update query: '{processed_query_for_search}'")
        similar_chunks_payloads = self.vector_store.search_similar_chunks(embedding=query_embedding, limit=5) # Limit can be adjusted

        if not similar_chunks_payloads:
             return {"status": "info", "message": "No relevant code chunks found for the query. Cannot suggest changes."}

        code_chunks_for_llm = [{
            "file_path": payload.get("file_path", "Unknown"),
            "content": payload.get("content", "No content available for this chunk."),
            "start_line": payload.get("start_line"), # Ensure this is consistently available
            "end_line": payload.get("end_line"),     # Ensure this is consistently available
            "type": payload.get("type"),   
            "name": payload.get("name")
            } for payload in similar_chunks_payloads]
            

        # code_chunks_for_llm = [{'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\routes\\web.php', 'content': "Route::post('/leaves/{id}/approve', [LeaveController::class, 'approve'])->name('leaves.approve')"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function approve($id) {\n        $leave = Leave::findOrFail($id);\n        $leave->status = 'approved';\n        $leave->save();\n        return back();\n    }"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function applyForm() {\n        return view('leave.apply');\n    }"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\resources\\views\\leave\\index.blade.php', 'content': '<h1>All Leave Applications</h1>\n@foreach($leaves as $leave)\n    <p>{{ $leave->employee_name }} | {{ $leave->start_date }} to {{ $leave->end_date }} | {{ $leave->status }}</p>\n    <form method="POST" action="{{ route(\'leaves.approve\', $leave->id) }}">@csrf<button>Approve</button></form>\n    <form method="POST" action="{{ route(\'leaves.reject\', $leave->id) }}">@csrf<button>Reject</button></form>\n@endforeach\n'}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function index() {\n        return view('leave.index', ['leaves' => Leave::all()]);\n    }"}]
        # code_chunks_for_llm = [{'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\routes\\web.php', 'content': "Route::post('/leaves/{id}/approve', [LeaveController::class, 'approve'])->name('leaves.approve')"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function approve($id) {\n        $leave = Leave::findOrFail($id);\n        $leave->status = 'approved';\n        $leave->save();\n        return back();\n    }"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function applyForm() {\n        return view('leave.apply');\n    }"}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\resources\\views\\leave\\index.blade.php', 'content': '<h1>All Leave Applications</h1>\n@foreach($leaves as $leave)\n    <p>{{ $leave->employee_name }} | {{ $leave->start_date }} to {{ $leave->end_date }} | {{ $leave->status }}</p>\n    <form method="POST" action="{{ route(\'leaves.approve\', $leave->id) }}">@csrf<button>Approve</button></form>\n    <form method="POST" action="{{ route(\'leaves.reject\', $leave->id) }}">@csrf<button>Reject</button></form>\n@endforeach\n'}, {'file_path': 'D:\\codes\\langGraph_venv\\code_assistant\\temp_code_uploads\\leave-management-laravel\\app\\Http\\Controllers\\LeaveController.php', 'content': "public function index() {\n        return view('leave.index', ['leaves' => Leave::all()]);\n    }"}]
        try:
            diff_output = self.llm_model.generate_code_diff(user_query=query, context_chunks=code_chunks_for_llm)
            LOGGER.info(f"LLM generated diff:\n{diff_output}")
            # Basic check if LLM returned something that looks like a diff or an explanation
            if not diff_output or diff_output.strip().startswith("#") or not any(line.startswith(('--- ', '+++ ', '@@ ')) for line in diff_output.splitlines()):
                 return {"status": "info", "message": "LLM did not generate a valid diff.", "diff": diff_output}

        except Exception as e:
            return {"status": "error", "message": f"Error generating diff with LLM: {e}"}

        # 3. Apply the diff
        try:
            # Use the patch library function
            apply_results = self.apply_diff_with_unidiff(diff_output, self.current_project_path)
            # apply_results = self.apply_diff_with_patch_lib(diff_output, self.current_project_path)
            # apply_results = self.apply_diff_with_patch_command(diff_output, self.current_project_path)
            # apply_results = self.apply_diff_with_patch_command(diff_output, self.current_project_path)
            
            # Check if any patch application failed or warned
            overall_status = "success"
            messages = ["Code changes suggested and application attempted."]
            for res in apply_results:
                 messages.append(f"  File {res['file_path']}: {res['status']} - {res['message']}")
                 if res['status'] == 'error':
                      overall_status = "error"
                 elif res['status'] == 'warning' and overall_status != 'error':
                      overall_status = "warning"

            return {"status": overall_status, "message": "\n".join(messages), "diff": diff_output, "apply_results": apply_results}

        except Exception as e:
            # This catch is for errors *before* the patch library starts processing files
            return {"status": "error", "message": f"An unexpected error occurred before applying diff: {e}", "diff": diff_output}


    def apply_diff_with_patch_command(self, diff_content: str, project_root: str) -> List[Dict[str, Any]]:
        diff_path = os.path.join(project_root, "temp_patch.diff")
        with open(diff_path, "w", encoding="utf-8") as f:
            f.write(diff_content)

        try:
            result = subprocess.run(
                ["patch", "-p1", "-i", diff_path],
                cwd=project_root,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            if result.returncode == 0:
                return [{"status": "success", "message": result.stdout}]
            else:
                return [{"status": "error", "message": result.stderr}]
        finally:
            os.remove(diff_path)

    
    # Define apply_diff_with_patch_lib function here
    def apply_diff_with_patch_lib(self, diff_content: str, project_root: str) -> List[Dict[str, Any]]:
        """
        Applies a unified diff string to files within the project root using the 'patch' library.
        ... (function implementation as provided in the thought block above) ...
        """
        results = []
        try:
            # The patch library expects bytes or a file object
            # Use io.StringIO to treat the string as a file
            patch_file_like = io.StringIO(diff_content)
            # Need to reset the stream position to the beginning after creating it
            patch_file_like.seek(0)
            patch_set = PatchSet(patch_file_like)

            if not patch_set:
                 results.append({"file_path": "N/A", "status": "error", "message": "Could not parse diff content. The diff might be empty or malformed."})
                 return results

            for p_item in patch_set: # Renamed 'p' to 'p_item' to avoid conflict with 'patch' module
                # p_item.path is the path from the diff (e.g., 'a/app/file.php' or 'app/file.php')
                # We need to determine the actual target path relative to project_root
                # Assuming LLM generates paths like `a/path` and `b/path`, we strip the first component.
                # The patch library's `apply` method takes `root` and `strip`.
                # `strip=1` removes the 'a/' or 'b/' prefix.
                # `root=project_root` makes the library look for the file relative to this root.

                try:
                    target_file_relative_to_diff = p_item.path # This is like 'a/app/file.php'
                    path_components = target_file_relative_to_diff.split(os.sep)
                    
                    # Ensure path has at least 'a/' or 'b/' prefix and a filename
                    if len(path_components) < 2: 
                         results.append({"file_path": p_item.path, "status": "error", "message": f"Invalid path format in diff: {p_item.path}. Expected 'a/path/to/file' or 'b/path/to/file'."})
                         continue

                    target_file_relative_to_root = os.sep.join(path_components[1:])
                    target_file_absolute_path = os.path.join(project_root, target_file_relative_to_root)

                    if not os.path.exists(target_file_absolute_path) and not p_item.is_added_file():
                         results.append({"file_path": p_item.path, "status": "error", "message": f"Target file for modification not found: {target_file_absolute_path}"})
                         continue
                    
                    # Ensure parent directory exists for new files
                    if p_item.is_added_file():
                        os.makedirs(os.path.dirname(target_file_absolute_path), exist_ok=True)

                    LOGGER.info(f"Attempting to apply patch to: {target_file_absolute_path}")
                    success = p_item.apply(strip=1, root=project_root) 

                    if success is True:
                         results.append({"file_path": p_item.path, "status": "success", "message": "Patch applied successfully."})
                    elif success is False: 
                         results.append({"file_path": p_item.path, "status": "warning", "message": "Patch application failed or applied with fuzz (context lines might not have matched exactly)."})
                    else: 
                         results.append({"file_path": p_item.path, "status": "warning", "message": f"Patch application returned unexpected result: {success}"})

                except Exception as e_apply:
                     results.append({"file_path": p_item.path, "status": "error", "message": f"An unexpected error occurred during patch application for {p_item.path}: {e_apply}"})

        except Exception as e_parse:
            results.append({"file_path": "N/A", "status": "error", "message": f"Error parsing or processing diff content: {e_parse}"})

        return results
    
    def apply_diff_with_unidiff(self, diff_content: str, project_root: str) -> List[Dict[str, Any]]:
        """
        Applies a unified diff string to files within the project root using the 'unidiff' library.
        Returns a list of results indicating success or failure for each file.
        """
        results = []
        diff_path = os.path.join(project_root, "temp_patch.diff")
        with open(diff_path, "w", newline="\n", encoding="utf-8") as f:
            f.write(diff_content)

        try:
            with open(diff_path, "r", encoding="utf-8") as f:
                patch_set = PatchSet(f)
                LOGGER.info("Parsed OK", patch_set)

            for patched_file in patch_set:
                target_path =  patched_file.path
                # Strip 'a/' or 'b/' prefix if present
                # path_parts = patched_file.path.split(os.sep)
                # relative_path = os.sep.join(path_parts[1:]) if len(path_parts) > 1 and path_parts[0] in ("a", "b") else patched_file.path
                # target_path = f"{project_root}/{relative_path}"

                if patched_file.is_removed_file:
                    if os.path.exists(target_path):
                        os.remove(target_path)
                        results.append({"file_path": target_path, "status": "success", "message": "File removed."})
                    else:
                        results.append({"file_path": target_path, "status": "warning", "message": "File marked for removal not found."})
                    continue

                if not patched_file.is_added_file and not os.path.exists(target_path):
                    results.append({"file_path": target_path, "status": "error", "message": "Original file does not exist."})
                    continue

                if patched_file.is_added_file:
                    os.makedirs(os.path.dirname(target_path), exist_ok=True)
                    original_lines = []
                else:
                    with open(target_path, "r", encoding="utf-8") as f:
                        original_lines = f.readlines()

                patched_lines = original_lines.copy()
                line_offset = 0

                for hunk in patched_file:
                    # Calculate the start of the hunk in the file
                    hunk_start = hunk.source_start - 1 + line_offset
                    # Extract only the lines from the hunk that are context or removed
                    expected_lines = [line.value for line in hunk if line.is_context or line.is_removed]
                    # Extract lines from the actual file at that point
                    actual_lines = patched_lines[hunk_start:hunk_start + len(expected_lines)]

                    def normalize(line: str):
                        line = line.replace('\t', '    ')             # Convert tabs to spaces
                        line = re.sub(r'\s*\{', ' {', line)           # Collapse spaces before {
                        return line.strip()
                       
                    
                    def is_similar(a: str, b: str, threshold: float = 0.95) -> bool:
                        return SequenceMatcher(None, normalize(a), normalize(b)).ratio() >= threshold
                    
                    # macthing diff content with original code for safe updation
                    matched = all(
                        is_similar(exp, act)
                        for exp, act in zip(expected_lines, actual_lines)
                    )

                    # for old_line, patch_line in zip([line for line in hunk if line.is_context or line.is_removed], actual_lines):
                    #     LOGGER.info(f"LINE: {normalize(old_line.value)}\nline: {normalize(patch_line)}")
                    #     if normalize(old_line.value) != normalize(patch_line):
                    #         break

                        
                    if not matched:
                        results.append({"file_path": target_path, "status": "error", "message": f"Hunk did not match context lines at line {hunk_start + 1}"})
                        break

                    # Apply hunk
                    hunk_len = len(expected_lines) or hunk.source_length
                    new_lines = [line.value for line in hunk if line.is_context or line.is_added]
                    patched_lines[hunk_start:hunk_start + hunk_len] = new_lines
                    line_offset += len(new_lines) - hunk_len

                else:
                    # Write back modified file if all hunks applied
                    # runs if the for loop for pacthed files runs successfully
                    with open(target_path, "w", encoding="utf-8") as f:
                        f.writelines(patched_lines)
                    results.append({"file_path": target_path, "status": "success", "message": "Patch applied."})

        except Exception as e:
            results.append({"file_path": "N/A", "status": "error", "message": str(e)})

        return results