
from enum import Enum
from typing import Any, Dict, List
from pydantic import BaseModel, Field

class UploadRequest(BaseModel):
    filename: str
    description: str

class QueryRequest(BaseModel):
    question: str

class UploadResponse(BaseModel):
    message: str
    filename: str
    description: str
    # extracted_files: list[str]


class ChunkResponse(BaseModel):
    file_name: str
    chunk: str

class CodeReference(BaseModel):
    file_name: str = Field(description="The path to the relevant code file.")
    code_content: str = Field(description="The content of the relevant code chunk.")

class LLMQueryResponse(BaseModel):
    explanation: str = Field(description="The textual explanation generated by the LLM in response to the user's query and provided context.")
    code_references: List[CodeReference] = Field(default_factory=list, description="A list of code chunks that were most relevant and used to formulate the explanation.")


class QueryResponse(BaseModel):
    question: str
    llm_answer: LLMQueryResponse = Field(description="The structured answer generated by the language model, including explanation and code references.")
    retrieved_chunks: List[ChunkResponse] = Field(description="List of code chunks retrieved by semantic search.")
    relevant_chunks_found: int = Field(description="Number of relevant chunks found.")


class CodeChunk(BaseModel):
    """Represents a meaningful chunk of Laravel code"""
    type: str  # 'controller', 'model', 'route', 'migration', etc.
    name: str
    file_path: str
    start_line: int
    end_line: int
    content: str
    metadata: Dict[str, Any]
    dependencies: List[str]

class UserQueryAnalysisType(Enum):
    GENERAL_ANSWER = "general_answer"
    REFINED_QUERY = "refined_query"
    ERROR = "error"
